---
- name: apt install wpasupplicant
  ansible.builtin.apt: name=wpasupplicant state=present
  become: true

- name: systemctl daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

