---
- name: pacman -Syu
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true
  when: ansible_facts["distribution"] == "Archlinux"

- name: dnf update
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  when: ansible_facts["distribution"] == "Fedora"

- name: apt update && apt dist-upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  become: true
  when: ansible_facts["distribution"] == "Debian"

