---
- name: grafana and prometheus config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.grafana_prometheus_config_dir }}/{{ item }}"
    state: directory
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true
  loop:
    - grafana
    - prometheus

- name: Copy prometheus.yml file
  ansible.builtin.copy:
    src: "{{ podman_user.prometheus_yml }}"
    dest: "{{ podman_user.grafana_prometheus_config_dir }}/prometheus.yml"
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true

- name: grafana prometheus containers
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/home/{{ podman_user.name }}/.config/containers/systemd/{{ item }}"
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"
  loop:
    - grafana-prometheus.pod
    - prometheus-server.container
    - prometheus-node-exporter.container
    - grafana.container

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now grafana-prometheus-pod.service
  ansible.builtin.systemd: name=grafana-prometheus-pod.service state=started enabled=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: systemctl --user enable --now prometheus-node-exporter.service
  ansible.builtin.systemd: name=prometheus-node-exporter.service state=started enabled=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - podman_user.prometheus_host_mode is defined
    - podman_user.prometheus_host_mode

